/**
 * Generate the launch overlay (`cordis.yml`) and the tsdown banner id
 * (`packages/dsh-web-review/entry-name.json`) from this checkout's absolute path.
 *
 * The entry name MUST be the absolute path to the plugin package: `dsh web`
 * boots base.cordis.yml from apps/cli/config, and both the Loader and
 * client-modules resolve entry names against that anchor — only absolute
 * paths are self-resolving for an external package. The browser module
 * loader additionally requires the bundle's `__ModuleLoader__.load` id to
 * equal the boot-graph row id, so tsdown reads the same value from
 * entry-name.json. Moving the repo requires regenerating both files
 * (`pnpm gen-config`). Run with tsx: `tsx scripts/gen-config.ts`.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const entry = join(root, 'packages', 'dsh-web-review')

if (!existsSync(join(entry, 'package.json'))) {
  console.error(`gen-config: plugin package not found at ${entry}`)
  process.exit(1)
}

const cordisYaml = [
  '# Generated by scripts/gen-config.ts — do not edit by hand.',
  '# Regenerate with `pnpm gen-config` after moving the repo (entry name = absolute path).',
  '- insert:',
  '    - id: dsh-web-review',
  `      name: ${JSON.stringify(entry)}`,
  '',
].join('\n')
writeFileSync(join(root, 'cordis.yml'), cordisYaml)
mkdirSync(entry, { recursive: true })
writeFileSync(join(entry, 'entry-name.json'), `${JSON.stringify({ name: entry }, null, 2)}\n`)
console.log(`gen-config: cordis.yml + packages/dsh-web-review/entry-name.json -> ${entry}`)
